export enum ErrorCode {
  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_ALREADY_VERIFIED = 'USER_ALREADY_VERIFIED',
  USER_INACTIVE = 'USER_INACTIVE',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',
  VERIFICATION_TOKEN_MISSING = 'VERIFICATION_TOKEN_MISSING',
  EMAIL_SERVICE_UNAVAILABLE = 'EMAIL_SERVICE_UNAVAILABLE',

  // General
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
}
