export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_SKU_EXISTS = 'PRODUCT_SKU_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
}
