export enum ErrorCode {
  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_ALREADY_VERIFIED = 'USER_ALREADY_VERIFIED',
  USER_INACTIVE = 'USER_INACTIVE',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',
  VERIFICATION_TOKEN_MISSING = 'VERIFICATION_TOKEN_MISSING',
  EMAIL_SERVICE_UNAVAILABLE = 'EMAIL_SERVICE_UNAVAILABLE',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED = 'RESET_TOKEN_EXPIRED',

  // General
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',

  // Board
  BOARD_TYPE_INVALID = 'BOARD_TYPE_INVALID',
  BOARD_NOT_FOUND = 'BOARD_NOT_FOUND',
  BOARD_CODE_EXISTS = 'BOARD_CODE_EXISTS',
  BOARD_CODE_UPDATE_FORBIDDEN = 'BOARD_CODE_UPDATE_FORBIDDEN',
  NOT_BOARD_MEMBER = 'NOT_BOARD_MEMBER',
  INSUFFICIENT_BOARD_PERMISSION = 'INSUFFICIENT_BOARD_PERMISSION',
  COLUMNS_NOT_BELONG_TO_BOARD = 'COLUMNS_NOT_BELONG_TO_BOARD',
  BOARD_MEMBER_NOT_FOUND = 'BOARD_MEMBER_NOT_FOUND',
  CANNOT_REMOVE_LAST_ADMIN = 'CANNOT_REMOVE_LAST_ADMIN',

  // Card
  CARD_NOT_FOUND = 'CARD_NOT_FOUND',
  ASSIGNEE_NOT_BOARD_MEMBER = 'ASSIGNEE_NOT_BOARD_MEMBER',
  INVALID_DATE_RANGE = 'INVALID_DATE_RANGE',
  MOVE_CARD_MISSING_CURRENT = 'MOVE_CARD_MISSING_CURRENT',
  MOVE_CARD_INVALID_PREV = 'MOVE_CARD_INVALID_PREV',
  MOVE_CARD_DUPLICATE_IDS = 'MOVE_CARD_DUPLICATE_IDS',
  MOVE_CARD_PREV_MISMATCH = 'MOVE_CARD_PREV_MISMATCH',
  MOVE_CARD_NEXT_MISMATCH = 'MOVE_CARD_NEXT_MISMATCH',
  MOVE_CARD_WRONG_COLUMN = 'MOVE_CARD_WRONG_COLUMN',

  // Column
  COLUMN_NOT_FOUND = 'COLUMN_NOT_FOUND',
  CARDS_NOT_BELONG_TO_COLUMN = 'CARDS_NOT_BELONG_TO_COLUMN',

  // Version
  VERSION_NOT_FOUND = 'VERSION_NOT_FOUND',

  // Issue Type
  ISSUE_TYPE_NOT_FOUND = 'ISSUE_TYPE_NOT_FOUND',
  ISSUE_TYPE_NAME_EXISTS = 'ISSUE_TYPE_NAME_EXISTS',

  // Upload
  FILE_REQUIRED = 'FILE_REQUIRED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_UNSUPPORTED = 'FILE_TYPE_UNSUPPORTED',
  FILE_MAX_COUNT_EXCEEDED = 'FILE_MAX_COUNT_EXCEEDED',

  // Me / Profile
  INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD',

  // Board Invitation
  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_ALREADY_RESPONDED = 'INVITATION_ALREADY_RESPONDED',
  INVITATION_EMAIL_MISMATCH = 'INVITATION_EMAIL_MISMATCH',
  INVITATION_ALREADY_PENDING = 'INVITATION_ALREADY_PENDING',
  USER_ALREADY_MEMBER = 'USER_ALREADY_MEMBER',
}
