export enum ConfigKey {
  APP_FRONTEND_URL = 'app.frontendUrl',
  APP_PORT = 'app.port',
  APP_API_PREFIX = 'app.apiPrefix',
  APP_NODE_ENV = 'app.nodeEnv',
  APP_CORS_ORIGINS = 'app.corsOrigins',
  APP_BREVO_API_KEY = 'app.brevoApiKey',
  APP_MAIL_SENDER_EMAIL = 'app.mail.senderEmail',
  APP_MAIL_SENDER_NAME = 'app.mail.senderName',
  LOGGER_FILE_PATH = 'logger.filePath',
  LOGGER_MAX_FILES = 'logger.maxFiles',
  JWT_ACCESS_SECRET = 'jwt.accessSecret',
  JWT_REFRESH_SECRET = 'jwt.refreshSecret',
  JWT_ACCESS_EXPIRES_IN = 'jwt.accessExpiresIn',
  JWT_REFRESH_EXPIRES_IN = 'jwt.refreshExpiresIn',
  DATABASE_URL = 'database.url',
  REDIS_HOST = 'redis.host',
  REDIS_PORT = 'redis.port',
}
